/**
 * Created by main on 2018/11/20.
 */
export const TOGGLE_SETDRAWER = 'TOGGLE_SETDRAWER'
export const TOGGLE_DETAIL = 'TOGGLE_DETAIL'
export const TOGGLE_SEARCH_VIEW = 'TOGGLE_SEARCH_VIEW'
export const RECEVIVE_CURRENT_USER = 'RECEVIVE_CURRENT_USER'
export const TOGGLE_CHAT = 'TOGGLE_CHAT'
export const SET_BOOK_INFO = 'SET_BOOK_INFO'
export const SET_INDEX = 'SET_INDEX'
export const SET_RANKING = 'SET_RANKING'
export const SET_BOOK_SHELF = 'SET_BOOK_SHELF'
export const DEL_BOOK_SHELF = 'DEL_BOOK_SHELF'
